---
title: "R Notebook"
output: html_notebook
---
```{r}
knitr::opts_chunk$set(echo = TRUE)
SciViews::R
```

```{r}
?readxl::read_excel
```

```{r}
bourdon <- read("../data/etho_tp2.xlsx" , type = "xlsx")

```

## Test student
```{r}
t.test(bourdon$masse,
  alternative = "two.sided", mu = 0, conf.level = 0.95)
```


```{r}
t.test(bourdon$taille_cr,
  alternative = "two.sided", mu = 0, conf.level = 0.95)
```

```{r}
chart(data = bourdon, masse ~ "") +
  geom_boxplot() +
  geom_hline(yintercept = 0, col = "red") +
  xlab("") +
  ylab("Masse (g)")


```

```{r}
chart(data = bourdon, taille_cr ~ "") +
  geom_boxplot() +
  geom_hline(yintercept = 0, col = "red") +
  xlab("") +
  ylab("Taille de la cellule radiale (mm)")
  plotly::ggplotly()
```

## Test de correlation

### Taille cellule radiale
```{r}
cor.test(data = bourdon, ~ masse + taille_cr, alternative = "greater")
```





## Regression lineaire
```{r}
(lm. <- lm(data = bourdon, masse ~ taille_cr))
summary(lm.)
```
 
 
### Residuals vs fitted 
```{r}
lm. %>.%
  chart(broom::augment(.), .resid ~ .fitted) +
  geom_point() +
  geom_hline(yintercept = 0) +
  geom_smooth(se = FALSE, method = "loess", formula = y ~ x) +
  labs(x = "Fitted values", y = "Residuals") +
  ggtitle("Residuals vs Fitted")
```

### Normal Q-Q
```{r}
lm. %>.%
  chart(broom::augment(.), aes(sample = .std.resid)) +
  geom_qq() +
  geom_qq_line(colour = "darkgray") +
  labs(x = "Theoretical quantiles", y = "Standardized residuals") +
  ggtitle("Normal Q-Q")
```

### Scale-location
```{r}
lm. %>.%
  chart(broom::augment(.), sqrt(abs(.std.resid)) ~ .fitted) +
  geom_point() +
  geom_smooth(se = FALSE, method = "loess", formula = y ~ x) +
  labs(x = "Fitted values",
    y = expression(bold(sqrt(abs("Standardized residuals"))))) +
  ggtitle("Scale-Location")
```


```{r}
```


```{r}
```

